### ISSUE TITLE
Support high baud rates

### ISSUE THREAD

**Issue by tvdstaaij** [flagos/serialclient#2]
```
$ serialclient -p /dev/ttyUSB0 -s 115200
>> Interactive Console <<
Serial_client >
```

```
$ serialclient -p /dev/ttyUSB0 -s 921600
Parameter for --speed must satisfy given conditions (see description)
```

I am working with a device that runs on 921600 baud so this would be appreciated :)

**Comment by flagos** [comment]
Hi,

Thank you for your bug report. 

This parameter is limited to 256000 baud since it is based on documented limitation of ruby-serialport. But, after checking on the code of this library, it seems that, depending on the platform you are running on, this lib can support higher baudrate, and anyway, you will get a proper error message by the library if it's not supported by your operating system.

I will so remove this limitation and maybe, cross finger, it will work in your case ;-). 

I will update this ticket when it's done.

**Comment by flagos** [comment]
Implementation done. Gem will be pushed.

**Comment by flagos** [comment]
Gem 0.2.4 pushed.
